### ISSUE TITLE
Fix project setup

### ISSUE THREAD

**Issue by AdmiralZook** [GPH-Studios/CnR-Hunt#1]
Might be an issue with the version the project was created with, but on my end (with the most up-to-date Unity) I can't load the project from the repo.

**Comment by AdmiralZook** [comment]
I think this might be a thing with the .gitignore, may have blocked the file marking the directory as a Unity project.

**Comment by gyogan** [comment]
OOO. Will check this when I return on Friday. Added you as collaborator.

**Comment by gyogan** [comment]
Version issues fixed as of ec14d34-- Official project version is "2018.1.6f1" 
Metadata files also now no longer being tracked.
